const albums = [
  {
    Title: 'Animals as Leaders',
    Artist: 'Animals as Leaders',
    Rating: 'Platinum',
    Descriptors: 'futuristic, instrumental',
    'Release Date': '2009-04-28',
    Spotify: 'https://open.spotify.com/album/1BRtQtljRJIxroJXI20K39',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=H6MxZzDKG8Q',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27393bb9d619c92bcd6ba242c39',
  },
  {
    Title: 'The Joy of Motion',
    Artist: 'Animals as Leaders',
    Rating: 'Platinum',
    Descriptors: 'futuristic, instrumental',
    'Release Date': '2014',
    Spotify: 'https://open.spotify.com/album/6N9IuJzAOwbzPx9oM0ar0j',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273a6b8eeff8cf7c0df77813234',
  },
  {
    Title: 'Jane Doe',
    Artist: 'Converge',
    Rating: 'Platinum',
    Descriptors: 'chaotic, harsh, prog',
    'Release Date': '2001',
    Spotify: 'https://open.spotify.com/album/2gtM4m6sglJDrX3toJWZO6',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=gU1bdx8nwZk',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2738de9ae6244861b7a0001fa3d',
  },
  {
    Title: 'The Money Store',
    Artist: 'Death Grips',
    Rating: 'Platinum',
    Descriptors: 'chaotic, futuristic',
    'Release Date': '2012-04-23',
    Spotify: 'https://open.spotify.com/album/1PQDjdBpHPikAodJqjzm6a',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=kxWlXxTM0yI',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273b4f8459b0f719f8a97ee1c8c',
  },
  {
    Title: 'Dopethrone',
    Artist: 'Electric Wizard',
    Rating: 'Platinum',
    Descriptors: 'atmospheric, depressing',
    'Release Date': '2006',
    Spotify: 'https://open.spotify.com/album/1AxwLCMtx8rnIxkFQKU2LO',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=eaMbKZPBruU',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273d11797b2bfbfefe908e0ad92',
  },
  {
    Title: 'Cosmogramma',
    Artist: 'Flying Lotus',
    Rating: 'Platinum',
    Descriptors: 'adventurous, futuristic, instrumental',
    'Release Date': '2010-05-03',
    Spotify: 'https://open.spotify.com/album/26yWpyWgFK6xuxi1UsLUFW',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=Pj60TMCWs1w',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2736f0c962b04f02c839726f41f',
  },
  {
    Title: 'Neō Wax Bloom',
    Artist: 'Iglooghost',
    Rating: 'Platinum',
    Descriptors: 'chaotic, fun, futuristic, instrumental',
    'Release Date': '2017-09-29',
    Spotify: 'https://open.spotify.com/album/68aZtDbgNargCMYgNvw5JG',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=CaVdFZstnPM',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2730c67ab993d8e939e97cf7a3f',
  },
  {
    Title: 'Nothing',
    Artist: 'Meshuggah',
    Rating: 'Platinum',
    Descriptors: 'breakdowns, prog',
    'Release Date': '2002-09-16',
    Spotify: 'https://open.spotify.com/album/0fBHkqXe7Ij5FAdYnMrIjY',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=umWGqu2rHR8',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27314940d2941f68b107da9eee4',
  },
  {
    Title: 'obZen',
    Artist: 'Meshuggah',
    Rating: 'Platinum',
    Descriptors: 'breakdowns, prog',
    'Release Date': '2008-03-07',
    Spotify: 'https://open.spotify.com/album/3XIgSzrNeDVXVc8LwP7axB',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=BNv6mk2Zc24',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27357669e4d1c2825c21a60fb84',
  },
  {
    Title: 'Filth Pig',
    Artist: 'Ministry',
    Rating: 'Platinum',
    Descriptors: 'depressing',
    'Release Date': '1996-01-26',
    Spotify: 'https://open.spotify.com/album/6pK142b1OANbpbyJ6XIuvo',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=VPjzDsRot78',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273ad44567084d3f95921886dad',
  },
  {
    Title: 'Loveless',
    Artist: 'my bloody `valentine',
    Rating: 'Platinum',
    Descriptors: 'atmospheric, soothing',
    'Release Date': '1991-11-04',
    Spotify: 'https://open.spotify.com/album/3GH4IiI6jQAIvnHVdb5FB6',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=jWJoMLJoZRQ',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2730ede770070357575bc050511',
  },
  {
    Title: 'Run the Jewels 2',
    Artist: 'Run the Jewels',
    Rating: 'Platinum',
    Descriptors: 'fun, futuristic',
    'Release Date': '2014-10-27',
    Spotify: 'https://open.spotify.com/album/07h5cYnfQm4mCDmEBiRtei',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=nnbyzr9Wbqs',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2739742a327795c8c656d4c436d',
  },
  {
    Title: 'End Position',
    Artist: 'Street Sects',
    Rating: 'Platinum',
    Descriptors: 'chaotic, harsh',
    'Release Date': '2016-09-16',
    Spotify: 'https://open.spotify.com/album/0qnkPX1fxM6hEnnVIl4Jw7',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27356c861ea95f473d5732c17a7',
  },
  {
    Title: 'Pelagial',
    Artist: 'The Ocean',
    Rating: 'Platinum',
    Descriptors: 'adventurous, prog',
    'Release Date': '2013-04-30',
    Spotify: 'https://open.spotify.com/album/6R9cHdJ7hljxDDYq2tUCdO',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=JfZMTDcqKnQ',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273dfa0bfe98aafc414ba96a96b',
  },
  {
    Title: 'The Fat of the Land',
    Artist: 'The Prodigy',
    Rating: 'Platinum',
    Descriptors: 'fun, futuristic',
    'Release Date': '1997-06-30',
    Spotify: 'https://open.spotify.com/album/2qivROlvQ8BcUKTaCA7dL2',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=1iPS6isM1ik',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2737bb4dd1d02346ec2321a41d6',
  },
  {
    Title: 'errorzone',
    Artist: 'Vein.fm',
    Rating: 'Platinum',
    Descriptors: 'breakdowns, fun',
    'Release Date': '2018-06-22',
    Spotify: 'https://open.spotify.com/album/5KSIgVF5lx4JURkS50jRS9',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=74tMFlXEETU',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273af89ca043be8fd7637b54df5',
  },
  {
    Title: 'Utd. State 90',
    Artist: '808 State',
    Rating: 'Gold',
    Descriptors: 'futuristic, instrumental, retro',
    'Release Date': '1990-06-11',
    Spotify: 'https://open.spotify.com/album/7DWTuqhMmJIE9Py0e8Wa5C',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=pQG7BNft418',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2736d57c4e0b9a2c77926f7b58c',
  },
  {
    Title: 'ex:el',
    Artist: '808 State',
    Rating: 'Gold',
    Descriptors: 'futuristic, instrumental, retro',
    'Release Date': '1991-03-01',
    Spotify: 'https://open.spotify.com/album/5q3FCcPTqLUT0UkrqMb45z',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=0qrfc3cjV_Q',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273f65021548f0f2112f86f8d57',
  },
  {
    Title: 'The Impossible Kid',
    Artist: 'Aesop Rock',
    Rating: 'Gold',
    Descriptors: 'futuristic',
    'Release Date': '2016-04-29',
    Spotify: 'https://open.spotify.com/album/6D6v19wYlLDsYkkfebOY3g',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=PQF6x_FgnJ0',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27323e2c8d614852bafd97629b5',
  },
  {
    Title: 'Supermodified',
    Artist: 'Amon Tobin',
    Rating: 'Gold',
    Descriptors: 'futuristic, instrumental',
    'Release Date': '2000-05-16',
    Spotify: 'https://open.spotify.com/album/54zaC0AviuCfkDwHsUJIra',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=W6M5_sCIIYI',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27314b74358028a458cc883b8ef',
  },
  {
    Title: 'Foley Room',
    Artist: 'Amon Tobin',
    Rating: 'Gold',
    Descriptors: 'futuristic, instrumental',
    'Release Date': '2007-02-26',
    Spotify: 'https://open.spotify.com/album/6o7OzvIJJMkhgB1QtEB1fj',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=vjr1d-OOq3o',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2736841c8f2dfa5290983e76e5c',
  },
  {
    Title: 'Out From Out Where',
    Artist: 'Amon Tobin',
    Rating: 'Gold',
    Descriptors: 'futuristic, instrumental',
    'Release Date': '2002-10-14',
    Spotify: 'https://open.spotify.com/album/27ftYHLeunzcSzb33Wk1hf',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=xEyCGHKJpPc',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2739236314a5d47e2b2277ca028',
  },
  {
    Title: 'Weightless',
    Artist: 'Animals as Leaders',
    Rating: 'Gold',
    Descriptors: 'futuristic, instrumental',
    'Release Date': '2011-11-08',
    Spotify: 'https://open.spotify.com/album/7IoPLwGpntUE7VaEXEU67i',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=-zM1WNAWsSs',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273eda0d4ce815da9d0100561ba',
  },
  {
    Title: 'Paul’s Boutique',
    Artist: 'Beastie Boys',
    Rating: 'Gold',
    Descriptors: 'fun',
    'Release Date': '1989-07-25',
    Spotify: 'https://open.spotify.com/album/1kmyirVya5fRxdjsPFDM05',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=iySa7HTWgSI',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2732288f4cd4bf3a8764624a0d2',
  },
  {
    Title: 'Colors',
    Artist: 'Between the Buried and Me',
    Rating: 'Gold',
    Descriptors: 'adventurous, prog',
    'Release Date': '2021-08-20',
    Spotify: 'https://open.spotify.com/album/6vC3CeC5FprLHnTZobbdee',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=iKspTicj-2w',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27310a4326cfae7ada4ba1dad1e',
  },
  {
    Title: 'Black Sands',
    Artist: 'Bonobo',
    Rating: 'Gold',
    Descriptors: 'instrumental, soothing',
    'Release Date': '2010-03-29',
    Spotify: 'https://open.spotify.com/album/5m1RkwKeU7MV0Ni6PH2lPy',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=-RbSogwKY94',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2737da6d6787071a97593cfbcee',
  },
  {
    Title: 'Meta',
    Artist: 'Car Bomb',
    Rating: 'Gold',
    Descriptors: 'chaotic, prog',
    'Release Date': '2016-10-28',
    Spotify: 'https://open.spotify.com/album/2VXwYjBFtwA3PF8OVyGs5w',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=XTfJREP_k3o',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27302817738bfc59f3f7f81665b',
  },
  {
    Title: 'Monolith of Inhumanity',
    Artist: 'Cattle Decapitation',
    Rating: 'Gold',
    Descriptors: 'breakdowns',
    'Release Date': '2012-05-08',
    Spotify: 'https://open.spotify.com/album/4aQI0KeN26jZ5bPQXKtfAa',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=XgwrYUFsLCY',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27350c5cba90147cca849c763c3',
  },
  {
    Title: 'The Anthropocene Extinction',
    Artist: 'Cattle Decapitation',
    Rating: 'Gold',
    Descriptors: 'breakdowns',
    'Release Date': '2015-08-07',
    Spotify: 'https://open.spotify.com/album/4QUiNabvDucY1hn8LRmbGd',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=RF-W8Dbtacs',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2734e3e65920636b519277c5055',
  },
  {
    Title: 'Forever',
    Artist: 'Code Orange',
    Rating: 'Gold',
    Descriptors: 'breakdowns',
    'Release Date': '2017-01-13',
    Spotify: 'https://open.spotify.com/album/2V7axnEU5HQoN9Tu5JVl4S',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=nKZ6Si57lPE',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2738ec7a604cd160e4f5b05d01a',
  },
  {
    Title: 'You Fail Me',
    Artist: 'Converge',
    Rating: 'Gold',
    Descriptors: 'breakdowns, prog',
    'Release Date': '2016-06-17',
    Spotify: 'https://open.spotify.com/album/3wOokyD0PiNT4CkaUnqdse',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=CeWDfSFcwf4',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2737250c4761f8aa168ef8db97d',
  },
  {
    Title: 'The Dusk in Us',
    Artist: 'Converge',
    Rating: 'Gold',
    Descriptors: 'prog',
    'Release Date': '2017-11-03',
    Spotify: 'https://open.spotify.com/album/23cl7dningjCbwiNpOyFMP',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=-wHtUflR-68',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273d5fd09a5ed4bae6405ce6107',
  },
  {
    Title: 'Axe to Fall',
    Artist: 'Converge',
    Rating: 'Gold',
    Descriptors: 'prog',
    'Release Date': '2009-10-20',
    Spotify: 'https://open.spotify.com/album/0sAtQQ4Y2zewIIxFidHbVR',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=mIJB-9xeyq8',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27313dfb6ac92c44ac010e1d706',
  },
  {
    Title: 'All We Love We Leave Behind',
    Artist: 'Converge',
    Rating: 'Gold',
    Descriptors: 'adventurous, prog',
    'Release Date': '2012-10-09',
    Spotify: 'https://open.spotify.com/album/28DI3wfImTqTrHkPiOa0PI',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=t-vZRGK4FbI',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27366453b97af3d62148b1fdb5e',
  },
  {
    Title: 'Eye for an Eye',
    Artist: 'Corrosion of Conformity',
    Rating: 'Gold',
    Descriptors: 'breakdowns, raw, retro',
    'Release Date': '2012-06-11',
    Spotify: 'https://open.spotify.com/album/6MXrcKF4lcAeIVHyAlaI4n',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273aae925d16dc49d6e6f54a1de',
  },
  {
    Title: 'Crowbar',
    Artist: 'Crowbar',
    Rating: 'Gold',
    Descriptors: 'breakdowns, depressing',
    'Release Date': '2010-10-05',
    Spotify: 'https://open.spotify.com/album/2Uzza6ahhYEk2HHQfTV5so',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=xk7JSOx_U68',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2738daf82bcd4645257c0c47dc8',
  },
  {
    Title: 'None So Vile',
    Artist: 'Cryptopsy',
    Rating: 'Gold',
    Descriptors: 'breakdowns, harsh, prog',
    'Release Date': '1996-07-03',
    Spotify: 'https://open.spotify.com/album/0mZUAsioioz1zKB2ll6jFt',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=QBhLTYNKUbo',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273c50fe8f1856c1111c0bb5287',
  },
  {
    Title: 'Mariner',
    Artist:
      'Cult of Luna, Julie Christmas (https://www.notion.so/Julie-Christmas-16493eb1d95e8007a68bd32491f389ce?pvs=21)',
    Rating: 'Gold',
    Descriptors: 'atmospheric, depressing, soothing',
    'Release Date': '2016-04-08',
    Spotify: 'https://open.spotify.com/album/1K1Uiyq8Qp9U5dRenhTaw9',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273409a7c131b0c6f31756395a2',
  },
  {
    Title: 'Old',
    Artist: 'Danny Brown',
    Rating: 'Gold',
    Descriptors: 'fun',
    'Release Date': '2013-10-08',
    Spotify: 'https://open.spotify.com/album/5SC0415RIGVX9ZfL0tfbAl',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=c4NuL0Q_r-w',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27368b3cdb0e859e5c1af35ddbd',
  },
  {
    Title: 'Atrocity Exhibition',
    Artist: 'Danny Brown',
    Rating: 'Gold',
    Descriptors: 'adventurous, fun',
    'Release Date': '2016-09-30',
    Spotify: 'https://open.spotify.com/album/3A1vnUJDPz0xYMful9pO4I',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=1sXk5Q2q_2M',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27306ce558a01af20d2837fb601',
  },
  {
    Title: 'Sunbather',
    Artist: 'Deafheaven',
    Rating: 'Gold',
    Descriptors: 'atmospheric',
    'Release Date': '2013-05-28',
    Spotify: 'https://open.spotify.com/album/2kKXGWaCEl06EKZ4DxBJIT',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=sgeGaM__ozA',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2739ad23cad3ef037b00c1d2a20',
  },
  {
    Title: 'Exmilitary',
    Artist: 'Death Grips',
    Rating: 'Gold',
    Descriptors: 'raw',
    'Release Date': '2012-04-23',
    Spotify: 'https://open.spotify.com/album/1PQDjdBpHPikAodJqjzm6a',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273b4f8459b0f719f8a97ee1c8c',
  },
  {
    Title: 'No Love Deep Web',
    Artist: 'Death Grips',
    Rating: 'Gold',
    Descriptors: 'breakdowns',
    'Release Date': '2012-10-01',
    Spotify: 'https://open.spotify.com/album/08aqY8lv4zx4uaqBUpMD8a',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=eu-MFuqymsc',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273f552daab2bc3dc64d2c4c649',
  },
  {
    Title: 'Government Plates',
    Artist: 'Death Grips',
    Rating: 'Gold',
    Descriptors: 'futuristic',
    'Release Date': '2013-11-13',
    Spotify: 'https://open.spotify.com/album/3T01oOjbrox1jz0pR112oV',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=E6mYEp1lWlE',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273dfab0b43e267fc2227be8502',
  },
  {
    Title: 'The Powers That B',
    Artist: 'Death Grips',
    Rating: 'Gold',
    Descriptors: 'atmospheric',
    'Release Date': '2015-02-10',
    Spotify: 'https://open.spotify.com/album/5Y04ylQjDWsawOUJXzY4YO',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2734aea9bda43e44a0e07f7c0b6',
  },
  {
    Title: 'White Pony',
    Artist: 'Deftones',
    Rating: 'Gold',
    Descriptors: 'atmospheric',
    'Release Date': '2000-05-16',
    Spotify: 'https://open.spotify.com/album/5LEXck3kfixFaA3CqVE7bC',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=v1npHeOskdQ',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2735c53799f473fa3e1a48c00ed',
  },
  {
    Title: 'Around the Fur',
    Artist: 'Deftones',
    Rating: 'Gold',
    Descriptors: 'atmospheric',
    'Release Date': '1997-10-27',
    Spotify: 'https://open.spotify.com/album/7o4UsmV37Sg5It2Eb7vHzu',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=8oVqeUzEcDA',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2730b1129853982ea17845d4eb6',
  },
  {
    Title: 'TA13OO',
    Artist: 'Denzel Curry',
    Rating: 'Gold',
    Descriptors: '808, adventurous, fun',
    'Release Date': '2018-07-27',
    Spotify: 'https://open.spotify.com/album/6idVoBWP2mt1qoMtASm3gc',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2737d05dd3ebb77cc048d66b294',
  },
  {
    Title: 'ZUU',
    Artist: 'Denzel Curry',
    Rating: 'Gold',
    Descriptors: '808, fun',
    'Release Date': '2019-05-31',
    Spotify: 'https://open.spotify.com/album/6PkSBdx19zarn4ae1D08gA',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=64EEpHCLEKU',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2735d46e4578c8e1adad9206480',
  },
  {
    Title: 'Are You Kidding Me? No.',
    Artist: 'Destrage',
    Rating: 'Gold',
    Descriptors: 'chaotic, fun',
    'Release Date': '2014-03-04',
    Spotify: 'https://open.spotify.com/album/2hgDsvHJwvPNjhXLL9ivcQ',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=ep-MOnxzhxA',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2733578cd4741e2acb84a8365c3',
  },
  {
    Title: 'Reign Supreme',
    Artist: 'Dying Fetus',
    Rating: 'Gold',
    Descriptors: 'breakdowns',
    'Release Date': '2012-06-19',
    Spotify: 'https://open.spotify.com/album/6SGhbpz7boAiDk9CotSDSD',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=HXKrj24YgUw',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27367c22e14a2f2adb1799f4748',
  },
  {
    Title: 'Cancer 4 Cure',
    Artist: 'El-P',
    Rating: 'Gold',
    Descriptors: 'futuristic',
    'Release Date': '2012',
    Spotify: 'https://open.spotify.com/album/75QfNfqa1LT0R5MIRKqR2q',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=GYwRCN40U24',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273d6f1e136647db2463b9b286e',
  },
  {
    Title: 'That Beast',
    Artist: 'ESA',
    Rating: 'Gold',
    Descriptors: 'harsh',
    'Release Date': '2018-03-09',
    Spotify: 'https://open.spotify.com/album/7ljXOMXc0NwNZzUXnmT7Y3',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=W-hka7uOKL4',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2738c6dac1fb7287e0b8ea68137',
  },
  {
    Title: 'The Nephilim',
    Artist: 'Fields of the Nephilim',
    Rating: 'Gold',
    Descriptors: 'atmospheric, soothing',
    'Release Date': '1988-09-05',
    Spotify: 'https://open.spotify.com/album/2m5896RbfEXpQGBfHkGYAP',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=lcGjhTIVy24',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2733d55b5c80bb1a8026bfce61e',
  },
  {
    Title: 'Elizium',
    Artist: 'Fields of the Nephilim',
    Rating: 'Gold',
    Descriptors: 'atmospheric, soothing',
    'Release Date': '1990',
    Spotify: 'https://open.spotify.com/album/5hFGua73w06tkEYkvA03kB',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2736f0a6d5093a4c2e0d82bb835',
  },
  {
    Title: 'Gray Data',
    Artist: 'Five Star Hotel',
    Rating: 'Gold',
    Descriptors: 'fun, harsh, queer',
    'Release Date': '2014-06-18',
    Spotify: 'https://open.spotify.com/album/6Q8hkb14PqvyLVEdmWXiD9',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=prXY-ZQdKJg',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273d4fcd0db8b5370308a28c265',
  },
  {
    Title: 'Machine Girl / Five Star Hotel',
    Artist: 'Five Star Hotel',
    Rating: 'Gold',
    Descriptors: 'futuristic, queer',
    'Release Date': '2016-10-31',
    Spotify: 'https://open.spotify.com/album/113KYCkSBJ4wMa497lShYS',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=3bHcYNW0azA',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2737709e08541d8827cb8eba85e',
  },
  {
    Title: 'Oxidized',
    Artist: 'Frontierer',
    Rating: 'Gold',
    Descriptors: 'chaotic, harsh',
    'Release Date': '2021-10-01',
    Spotify: 'https://open.spotify.com/album/7Ji7EoMriqTWUZYeHxMjOY',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=6tMY0UTICxY',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273a45ae6d71c38ad11a6fde43b',
  },
  {
    Title: 'Post Self',
    Artist: 'Godflesh',
    Rating: 'Gold',
    Descriptors: 'atmospheric, depressing',
    'Release Date': '2017-11-17',
    Spotify: 'https://open.spotify.com/album/4yLRI4kaOy4LhSPZ2sCVbE',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=yHYl1PmKg_M',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273fd2cd96e96c1146608b05a0e',
  },
  {
    Title: 'A World Lit Only By Fire',
    Artist: 'Godflesh',
    Rating: 'Gold',
    Descriptors: 'breakdowns, depressing',
    'Release Date': '2017-09-24',
    Spotify: 'https://open.spotify.com/album/1UbMFz1E6gcjrIvqohXoBk',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=271e9x5mVA8',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273fcfd37962c7f81c853406d20',
  },
  {
    Title: 'Songs of Love and Hate',
    Artist: 'Godflesh',
    Rating: 'Gold',
    Descriptors: 'breakdowns',
    'Release Date': '1996',
    Spotify: 'https://open.spotify.com/album/6WjveQqcQ9OOLG0OsalSPJ',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=bS90k_DnLgI',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2730cfe27bd70710fe3d49cdabf',
  },
  {
    Title: 'v2.0',
    Artist: 'GoGo Penguin',
    Rating: 'Gold',
    Descriptors: 'chaotic, fun, instrumental',
    'Release Date': '2014-03-17',
    Spotify: 'https://open.spotify.com/album/7rXrjbrYcXG8EkqXpt0weK',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=WKX8yJ4dx9k',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273a5e54268be71f1d22b5c5e60',
  },
  {
    Title: 'A Humdrum Star',
    Artist: 'GoGo Penguin',
    Rating: 'Gold',
    Descriptors: 'instrumental, soothing',
    'Release Date': '2018-02-09',
    Spotify: 'https://open.spotify.com/album/21TUXYHOeHVMOKbCuxzfKn',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=goJdoLE_1iY',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273ef39992622c059b03461aa8a',
  },
  {
    Title: 'From Mars to Sirius',
    Artist: 'Gojira',
    Rating: 'Gold',
    Descriptors: 'adventurous, breakdowns, prog',
    'Release Date': '2005-09-07',
    Spotify: 'https://open.spotify.com/album/0AvFF0HlQYvYKHaRURGZBs',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=3Y4_e5jWzCA',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273ec0c965c999ab968c912e099',
  },
  {
    Title: 'L’Enfant Sauvage',
    Artist: 'Gojira',
    Rating: 'Gold',
    Descriptors: 'adventurous, breakdowns, prog',
    'Release Date': '2012-06-26',
    Spotify: 'https://open.spotify.com/album/5dxqD5Kc6cRRi3rErmDfXG',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=Kf4eR4FVKzE',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2733ac9158414ee0e4042ffc56d',
  },
  {
    Title: 'The Way of All Flesh',
    Artist: 'Gojira',
    Rating: 'Gold',
    Descriptors: 'adventurous, breakdowns, prog',
    'Release Date': '2008-10-13',
    Spotify: 'https://open.spotify.com/album/4J79cxsmRqZbI0BKmNFDy2',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=Kf4eR4FVKzE',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273501ce8fe21aa2dc722600d8e',
  },
  {
    Title: 'Demon Days',
    Artist: 'Gorillaz',
    Rating: 'Gold',
    Descriptors: 'adventurous, fun',
    'Release Date': '2005-05-23',
    Spotify: 'https://open.spotify.com/album/0bUTHlWbkSQysoM3VsWldT',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=dC7zzhVXdWI',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27319d85a472f328a6ed9b704cf',
  },
  {
    Title: 'Dookie',
    Artist: 'Green Day',
    Rating: 'Gold',
    Descriptors: 'fun',
    'Release Date': '1994-02-01',
    Spotify: 'https://open.spotify.com/album/4uG8q3GPuWHQlRbswMIRS6',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=eXKFtu7KfC0',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273db89b08034de626ebee6823d',
  },
  {
    Title: "Lovers' Requiem",
    Artist: 'I Am Ghost',
    Rating: 'Gold',
    Descriptors: 'adventurous, prog',
    'Release Date': '2006-10-24',
    Spotify: 'https://open.spotify.com/album/4q9URYqANHG266gWgwlui3',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=XFXIur9yGAA',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273e2ad5812071205e20a0b6615',
  },
  {
    Title: 'Floss',
    Artist: 'Injury Reserve',
    Rating: 'Gold',
    Descriptors: 'futuristic',
    'Release Date': '2016-12-15',
    Spotify: 'https://open.spotify.com/album/67sUOjUevVJGgfCj1N2e4N',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=GXH-Ds6Tub0',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2735e66961c0acc955347d076bb',
  },
  {
    Title: 'I’m Scared',
    Artist: "Jacob's Mouse",
    Rating: 'Gold',
    Descriptors: 'fun',
    'Release Date': '1993-05-01',
    Spotify: 'https://open.spotify.com/album/1dqNaBZlz6mnWvPWxuvNHn',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273fa87e1f5625277fce73d2077',
  },
  {
    Title: 'All My Heroes Are Cornballs',
    Artist: 'JPEGMAFIA',
    Rating: 'Gold',
    Descriptors: 'soothing',
    'Release Date': '2019-09-13',
    Spotify: 'https://open.spotify.com/album/5ilsl5R2lGACTnPZMKIp7o',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=B4gqLcY6W0Y',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273c0f5083c53e881de8dec3d70',
  },
  {
    Title: 'Veteran',
    Artist: 'JPEGMAFIA',
    Rating: 'Gold',
    Descriptors: 'breakdowns, chaotic, harsh',
    'Release Date': '2018-01-19',
    Spotify: 'https://open.spotify.com/album/51WLEfPEEkzAWurvuY6Gco',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=uATMmh2NBSE',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273f8aaeba5e6dee1745371e822',
  },
  {
    Title: 'Night Time',
    Artist: 'Killing Joke',
    Rating: 'Gold',
    Descriptors: 'retro',
    'Release Date': '1985-02-11',
    Spotify: 'https://open.spotify.com/album/5VLAt18707WnG1UlJH7Z2f',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=oBj_GvzpmNo',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2730208ae0064b1de2bc955d566',
  },
  {
    Title: 'Meir',
    Artist: 'Kvelertak',
    Rating: 'Gold',
    Descriptors: 'fun',
    'Release Date': '2013-03-22',
    Spotify: 'https://open.spotify.com/album/1147s32sIAabDpmBeBf2bN',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=lPsNwhPIIHw',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27387e9b11459469217d7ca8d0a',
  },
  {
    Title: 'Static Tensions',
    Artist: 'Kylesa',
    Rating: 'Gold',
    Descriptors: 'adventurous',
    'Release Date': '2009-03-17',
    Spotify: 'https://open.spotify.com/album/5IcZbMCphgaFWXZ2EKCMHm',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=pFRirdsEDHo',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273bb1c157e6c1ae09e6da21aad',
  },
  {
    Title: 'Spiral Shadow',
    Artist: 'Kylesa',
    Rating: 'Gold',
    Descriptors: 'adventurous, atmospheric, prog',
    'Release Date': '2010',
    Spotify: 'https://open.spotify.com/album/2NNavvaS7LcOxryzfxSkgw',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2734436bb6c87320b8d7e4de237',
  },
  {
    Title: 'Physical Graffiti',
    Artist: 'Led Zeppelin',
    Rating: 'Gold',
    Descriptors: 'rock',
    'Release Date': '1975-02-24',
    Spotify: 'https://open.spotify.com/album/26tH0kjUhkxBEd3ipGkx3Y',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=EH6I31ev1GM',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273765b0617b572bdd1dbdc7d8e',
  },
  {
    Title: 'Led Zeppelin IV',
    Artist: 'Led Zeppelin',
    Rating: 'Gold',
    Descriptors: 'adventurous, rock',
    'Release Date': '1971-11-08',
    Spotify: 'https://open.spotify.com/album/44Ig8dzqOkvkGDzaUof9lK',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=LlDZ0AFN5C0',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273c8a11e48c91a982d086afc69',
  },
  {
    Title: 'Fantasy Empire',
    Artist: 'Lightning Bolt',
    Rating: 'Gold',
    Descriptors: 'chaotic, fun, harsh',
    'Release Date': '2015-03-24',
    Spotify: 'https://open.spotify.com/album/0Z0aI5ATk4kmQfTSANB0Z1',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=lsNObV962LA',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2737b6f8f86e9ff52aaca3cc82e',
  },
  {
    Title: 'Mista Thug Isolation',
    Artist: 'Lil Ugly Mane',
    Rating: 'Gold',
    Descriptors: '808, fun',
    'Release Date': '2012-02-11',
    Spotify: 'https://open.spotify.com/album/6VNXIYzXocTyZMNDLG88Gb',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=Fe5dGoVxpgM',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273b704e1460866f465fe8421cf',
  },
  {
    Title: 'Gala',
    Artist: 'Lush',
    Rating: 'Gold',
    Descriptors: 'atmospheric, soothing',
    'Release Date': '1990-11-12',
    Spotify: 'https://open.spotify.com/album/1UBjGsLtSkSMHlBkCc2OI4',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=QEK-f7zphlU',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273581bc388b3e8844db22a0612',
  },
  {
    Title: 'Madvillainy',
    Artist: 'Madvillain',
    Rating: 'Gold',
    Descriptors: 'atmospheric, fun, futuristic',
    'Release Date': '2004-03-24',
    Spotify: 'https://open.spotify.com/album/19bQiwEKhXUBJWY6oV3KZk',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=herNYSdJd0o',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273468f3f426419f48a8b8ab1e1',
  },
  {
    Title: 'Mezzanine',
    Artist: 'Massive Attack',
    Rating: 'Gold',
    Descriptors: 'atmospheric, soothing',
    'Release Date': '1998-01-01',
    Spotify: 'https://open.spotify.com/album/49MNmJhZQewjt06rpwp6QR',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=ORxdyjvfItk',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2732fcb0a3c7a66e516b11cd26e',
  },
  {
    Title: 'Leviathan',
    Artist: 'Mastodon',
    Rating: 'Gold',
    Descriptors: 'adventurous, prog',
    'Release Date': '2004-08-31',
    Spotify: 'https://open.spotify.com/album/6khFoLWnJZDQvZ7Pijym3b',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=4Kp0LxKTZhk',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27300388d66c87c2c0033849bfd',
  },
  {
    Title: 'Crack the Skye',
    Artist: 'Mastodon',
    Rating: 'Gold',
    Descriptors: 'adventurous, prog',
    'Release Date': '2009',
    Spotify: 'https://open.spotify.com/album/2W2nqEKXWBorbq5yvm3jZg',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=LdgnyYoZY3w',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273ac79283ccb6d08af31fd33d8',
  },
  {
    Title: 'Blood Mountain',
    Artist: 'Mastodon',
    Rating: 'Gold',
    Descriptors: 'adventurous, prog',
    'Release Date': '2006-09-08',
    Spotify: 'https://open.spotify.com/album/1n8QZFcwx5aQ2LIIlj0iYe',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=4W3JLsuA2yA',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273abe244c2bab281947c3209cc',
  },
  {
    Title: 'Remission',
    Artist: 'Mastodon',
    Rating: 'Gold',
    Descriptors: 'adventurous, prog',
    'Release Date': '2002-05-28',
    Spotify: 'https://open.spotify.com/album/1aQZecM7d2R3SvPs2HNNIA',
    Bandcamp: '',
    YouTube: 'https://youtube.com/watch?v=fsTptrKxVNk',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2737c967d6e87846a9fe277373f',
  },
  {
    Title: 'Rust in Peace',
    Artist: 'Megadeth',
    Rating: 'Gold',
    Descriptors: 'adventurous, fast',
    'Release Date': '1990-10-04',
    Spotify: 'https://open.spotify.com/album/0qaLL09EtF1hiUis7PRvaJ',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273be9fa5a89479b6af481938a0',
  },
  {
    Title: 'Peace Sells… But Who’s Buying?',
    Artist: 'Megadeth',
    Rating: 'Gold',
    Descriptors: 'adventurous, fast',
    'Release Date': '1986',
    Spotify: 'https://open.spotify.com/album/4U8ZF5zDIRy4lBnnXBN2uO',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2738fc06398d8852596d4981252',
  },
  {
    Title: 'Chaosphere',
    Artist: 'Meshuggah',
    Rating: 'Gold',
    Descriptors: 'breakdowns, fast, prog',
    'Release Date': '1998-11-09',
    Spotify: 'https://open.spotify.com/album/4Oow4gPOEJZfx8EI5Fb0eF',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273260028b0cf6dab6a567afa5c',
  },
  {
    Title: 'Catch ThirtyThree',
    Artist: 'Meshuggah',
    Rating: 'Gold',
    Descriptors: 'adventurous, prog',
    'Release Date': '2008-03-07',
    Spotify: 'https://open.spotify.com/album/3XIgSzrNeDVXVc8LwP7axB',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27357669e4d1c2825c21a60fb84',
  },
  {
    Title: '…And Justice For All',
    Artist: 'Metallica',
    Rating: 'Gold',
    Descriptors: 'adventurous, fast, prog',
    'Release Date': '1988-09-07',
    Spotify: 'https://open.spotify.com/album/2XbWaerVk9fjhEiGSrd6TF',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273be54746b374358970b5e617a',
  },
  {
    Title: 'Master of Puppets',
    Artist: 'Metallica',
    Rating: 'Gold',
    Descriptors: 'adventurous, fast, prog',
    'Release Date': '1986-03-03',
    Spotify: 'https://open.spotify.com/album/7CGhx630DIjdJqaBDVKc5j',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273cad4832cb7b5844343278daa',
  },
  {
    Title: 'Ride the Lightning',
    Artist: 'Metallica',
    Rating: 'Gold',
    Descriptors: 'adventurous, fast, prog',
    'Release Date': '1984-07-27',
    Spotify: 'https://open.spotify.com/album/2omIeSJEGQeKHPOpiXgfkr',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273533fd0b248052d04e6b732c0',
  },
  {
    Title: 'DOOM (Original Game Soundtrack)',
    Artist: 'Mick Gordon',
    Rating: 'Gold',
    Descriptors: 'breakdowns, futuristic, instrumental',
    'Release Date': '2016-09-28',
    Spotify: 'https://open.spotify.com/album/0KQyC28P9808r0oKKNgHvp',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273aad36b64a1a78951b504bc4e',
  },
  {
    Title: 'Psalm 69',
    Artist: 'Ministry',
    Rating: 'Gold',
    Descriptors: 'fun, harsh',
    'Release Date': '1992-07-10',
    Spotify: 'https://open.spotify.com/album/2wz3P1w89gQd3iXdmF1IA5',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27390edd2885a4865e0a4bf6f3c',
  },
  {
    Title: 'The Land of Rape and Honey',
    Artist: 'Ministry',
    Rating: 'Gold',
    Descriptors: 'harsh',
    'Release Date': '1988',
    Spotify: 'https://open.spotify.com/album/6TyCJQqyB8OZLhUEPCNgNT',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273da28d2ca0082549c2de71af3',
  },
  {
    Title: 'The Mind Is a Terrible Thing to Taste',
    Artist: 'Ministry',
    Rating: 'Gold',
    Descriptors: 'harsh',
    'Release Date': '1989-11-10',
    Spotify: 'https://open.spotify.com/album/2Z73HeYQNCf5T8dzzHaoz5',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273b24dc2f125c785d242029041',
  },
  {
    Title: 'Black On Both Sides',
    Artist: 'Mos Def',
    Rating: 'Gold',
    Descriptors: 'hip hop',
    'Release Date': '1999-10-12',
    Spotify: 'https://open.spotify.com/album/5gK2l2LgWY0BA4p9uy27z6',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27389b56f56323925d57b38944d',
  },
  {
    Title: 'The Art of Partying',
    Artist: 'Municipal Waste',
    Rating: 'Gold',
    Descriptors: 'breakdowns, fast, fun',
    'Release Date': '2007',
    Spotify: 'https://open.spotify.com/album/7cU3FZ3u2jgKd5s8hhKJ9h',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273760a0ad8dce3c88c9907352a',
  },
  {
    Title: 'Black Holes and Revelations',
    Artist: 'Muse',
    Rating: 'Gold',
    Descriptors: 'adventurous',
    'Release Date': '2006-06-19',
    Spotify: 'https://open.spotify.com/album/0lw68yx3MhKflWFqCsGkIs',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27328933b808bfb4cbbd0385400',
  },
  {
    Title: "Isn't Anything",
    Artist: 'my bloody valentine',
    Rating: 'Gold',
    Descriptors: 'atmospheric, soothing',
    'Release Date': '1988-11-21',
    Spotify: 'https://open.spotify.com/album/3mnv6nzZV5AQhDG7OUsLdo',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2733164437cb02167803e0f7f51',
  },
  {
    Title: 'Abandon All Life',
    Artist: 'Nails',
    Rating: 'Gold',
    Descriptors: 'chaotic, fast, harsh',
    'Release Date': '2013-03-19',
    Spotify: 'https://open.spotify.com/album/0HCZqugYM0BJmzsJJs5Mb5',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273469988dc10b5be4347897c22',
  },
  {
    Title: 'Nevermind',
    Artist: 'Nirvana',
    Rating: 'Gold',
    Descriptors: 'rock',
    'Release Date': '1991-09-26',
    Spotify: 'https://open.spotify.com/album/6yaiubHHJy8N8QcHy3julo',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273d27b5404a8aa5b94856e24cc',
  },
  {
    Title: 'Periphery II',
    Artist: 'Periphery',
    Rating: 'Gold',
    Descriptors: 'adventurous, breakdowns, prog',
    'Release Date': '2016-07-26',
    Spotify: 'https://open.spotify.com/album/5L9ddlTFtgLj93nzy77MEO',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273d38982d754066143f855d6dc',
  },
  {
    Title: 'Dos Dedos Mis Amigos',
    Artist: 'Pop Will Eat Itself',
    Rating: 'Gold',
    Descriptors: 'futuristic',
    'Release Date': '1994-01-01',
    Spotify: 'https://open.spotify.com/album/2ZWYbyMqlZZ8wyqe3GcJmz',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273ab84ca0a3df6071384b104f6',
  },
  {
    Title: 'Frizzle Fry',
    Artist: 'Primus',
    Rating: 'Gold',
    Descriptors: 'adventurous, chaotic, fun',
    'Release Date': '1990-02-07',
    Spotify: 'https://open.spotify.com/album/0bCjsDy7xtSGsKleQXF9ng',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2732416da30701c087d1905fef2',
  },
  {
    Title: 'So It Goes',
    Artist: 'Ratking',
    Rating: 'Gold',
    Descriptors: '808, atmospheric',
    'Release Date': '2014-04-07',
    Spotify: 'https://open.spotify.com/album/0wQpKLNavM2B8PZRMiO95X',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273323aaea936c1de287d852b48',
  },
  {
    Title: 'Murder the Mountains',
    Artist: 'Red Fang',
    Rating: 'Gold',
    Descriptors: 'fun, rock',
    'Release Date': '2011-04-12',
    Spotify: 'https://open.spotify.com/album/5RQlhjpn4qz3q2vRrAGYD9',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273363e08f434a00b57faa774e7',
  },
  {
    Title: 'Whales and Leeches',
    Artist: 'Red Fang',
    Rating: 'Gold',
    Descriptors: 'fun, rock',
    'Release Date': '2013-10-15',
    Spotify: 'https://open.spotify.com/album/2CtG0KacG7ZYR6PL5dD1jA',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2739122d59f5e5946c957d60086',
  },
  {
    Title: 'Red Fang',
    Artist: 'Red Fang',
    Rating: 'Gold',
    Descriptors: 'fun, rock',
    'Release Date': '2009-03-10',
    Spotify: 'https://open.spotify.com/album/1orQuQDeSCf7yEPSEAb6Gb',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273bc7bd2dafbd55237b170777c',
  },
  {
    Title: 'Blood Sugar Sex Magik',
    Artist: 'Red Hot Chili Peppers',
    Rating: 'Gold',
    Descriptors: 'fun',
    'Release Date': '1991-09-24',
    Spotify: 'https://open.spotify.com/album/30Perjew8HyGkdSmqguYyg',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273153d79816d853f2694b2cc70',
  },
  {
    Title: 'The Shape Of Punk To Come',
    Artist: 'Refused',
    Rating: 'Gold',
    Descriptors: 'adventurous, breakdowns, prog',
    'Release Date': '1998',
    Spotify: 'https://open.spotify.com/album/2Us9qPHLvLoTl6HkYAPcz2',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2735cc694ed1ca80fd696a0817e',
  },
  {
    Title: 'Ultu Ulla',
    Artist: 'Rings of Saturn',
    Rating: 'Gold',
    Descriptors: 'breakdowns, prog',
    'Release Date': '2017-07-28',
    Spotify: 'https://open.spotify.com/album/5IOuPXoAozgScwimBGA9b7',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2730d5181171fb934b8acfe3b5f',
  },
  {
    Title: 'RTJ4',
    Artist: 'Run the Jewels',
    Rating: 'Gold',
    Descriptors: 'fun, futuristic',
    'Release Date': '2020-06-03',
    Spotify: 'https://open.spotify.com/album/74LenWKjMdGa2qJiI1sxwT',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27342898aa855aa284ad4b2c1ff',
  },
  {
    Title: 'Run the Jewels 3',
    Artist: 'Run the Jewels',
    Rating: 'Gold',
    Descriptors: 'fun, futuristic',
    'Release Date': '2016-12-25',
    Spotify: 'https://open.spotify.com/album/2vY03PfKPFUUM1FA2lgmC2',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273d816781f1eb80793279e43b6',
  },
  {
    Title: 'Run the Jewels',
    Artist: 'Run the Jewels',
    Rating: 'Gold',
    Descriptors: 'fun, futuristic',
    'Release Date': '2016-12-25',
    Spotify: 'https://open.spotify.com/album/2vY03PfKPFUUM1FA2lgmC2',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273d816781f1eb80793279e43b6',
  },
  {
    Title: 'Moving Pictures',
    Artist: 'Rush',
    Rating: 'Gold',
    Descriptors: 'adventurous, prog, soothing',
    'Release Date': '1981-02-12',
    Spotify: 'https://open.spotify.com/album/2xg7iIKoSqaDNpDbJnyCjY',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27372833c1ae3343cbfb4617073',
  },
  {
    Title: 'The Migration',
    Artist: 'Scale the Summit',
    Rating: 'Gold',
    Descriptors: 'adventurous, prog, soothing',
    'Release Date': '2013-06-11',
    Spotify: 'https://open.spotify.com/album/2oL78CzVNt1WXsa0Etvpo7',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273ec1d8cc0240bc358e98dca03',
  },
  {
    Title: 'Chaos A.D.',
    Artist: 'Sepultura',
    Rating: 'Gold',
    Descriptors: 'breakdowns',
    'Release Date': '1993-09-02',
    Spotify: 'https://open.spotify.com/album/5r4qa5AIQUVypFRXQzjaiu',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2739c0b2d74cfb910735ca55317',
  },
  {
    Title: 'Seasons in the Abyss',
    Artist: 'Slayer',
    Rating: 'Gold',
    Descriptors: 'breakdowns, fast',
    'Release Date': '1990-01-01',
    Spotify: 'https://open.spotify.com/album/49QJ9TAWNqZGbFUvadXPgT',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273c0c12d83c0488024b66c9739',
  },
  {
    Title: 'Reign in Blood',
    Artist: 'Slayer',
    Rating: 'Gold',
    Descriptors: 'breakdowns, fast',
    'Release Date': '1986-01-01',
    Spotify: 'https://open.spotify.com/album/5v5BfkxWDAKTkzrXl3H0mU',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2731530f31c8d4197777b70ee5d',
  },
  {
    Title: 'No Cities to Love',
    Artist: 'Sleater-Kinney',
    Rating: 'Gold',
    Descriptors: 'fun',
    'Release Date': '2015-01-20',
    Spotify: 'https://open.spotify.com/album/7HDcY3h70X3zLjceUO874A',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2735385b525402ff1002a648044',
  },
  {
    Title: 'Vol. 3: The Subliminal Verses',
    Artist: 'Slipknot',
    Rating: 'Gold',
    Descriptors: 'breakdowns, fun',
    'Release Date': '2004',
    Spotify: 'https://open.spotify.com/album/4ZDBQSIDIZRUBOG2OHcN3T',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2736b3463e7160d333ada4b175a',
  },
  {
    Title: 'Slipknot',
    Artist: 'Slipknot',
    Rating: 'Gold',
    Descriptors: 'breakdowns, fast, fun',
    'Release Date': '2013-10-04',
    Spotify: 'https://open.spotify.com/album/75OGfvPnYgkBVCqmZcLy0n',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27314d6198dc2881c76fdfe24c6',
  },
  {
    Title: 'Doggystyle',
    Artist: 'Snoop Dogg',
    Rating: 'Gold',
    Descriptors: 'fun',
    'Release Date': '1993-11-23',
    Spotify: 'https://open.spotify.com/album/5IFOummNcGXY3qCBWRchqP',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273733af86f8dea9692a3f59d29',
  },
  {
    Title: 'Superunknown',
    Artist: 'Soundgarden',
    Rating: 'Gold',
    Descriptors: 'rock',
    'Release Date': '1994-03-09',
    Spotify: 'https://open.spotify.com/album/29sTacnS0qA9xri6YS8xLA',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273ae6d8e36136353d550b2587d',
  },
  {
    Title: 'Down on the Upside',
    Artist: 'Soundgarden',
    Rating: 'Gold',
    Descriptors: 'rock',
    'Release Date': '1996-05-21',
    Spotify: 'https://open.spotify.com/album/1IVa98im1RfxYp6qeOIg2B',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2736d70b73bcb327515e9fa8fac',
  },
  {
    Title: 'Cobra and Phases Group Play Voltage In the Milky Night',
    Artist: 'Stereolab',
    Rating: 'Gold',
    Descriptors: 'soothing',
    'Release Date': '1999',
    Spotify: 'https://open.spotify.com/album/4Amgy7JIX58geZLD6Wrz2r',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273f3e12f23c488f36105a86cb5',
  },
  {
    Title: 'I Should Coco',
    Artist: 'Supergrass',
    Rating: 'Gold',
    Descriptors: 'fun',
    'Release Date': '1995-05-15',
    Spotify: 'https://open.spotify.com/album/1MXoLMlKeGGVKdwARUuWRa',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273bd3a61b98a765e9b705110e6',
  },
  {
    Title: 'Filth',
    Artist: 'Swans',
    Rating: 'Gold',
    Descriptors: 'atmospheric, harsh',
    'Release Date': '1983-05-27',
    Spotify: 'https://open.spotify.com/album/70ff8ZgebUJWXQDzV5zVVk',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273c4e86a1cd9b4e8e4cb96e23f',
  },
  {
    Title: 'Steal This Album!',
    Artist: 'System of a Down',
    Rating: 'Gold',
    Descriptors: 'chaotic, fun',
    'Release Date': '2002-11-26',
    Spotify: 'https://open.spotify.com/album/6lA1sGw7eCv27bcpd5E0wT',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2737cf4c0d42c5b62c9deebdcd8',
  },
  {
    Title: 'Toxicity',
    Artist: 'System of a Down',
    Rating: 'Gold',
    Descriptors: 'chaotic',
    'Release Date': '2001-09-04',
    Spotify: 'https://open.spotify.com/album/6jWde94ln40epKIQCd8XUh',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27330d45198d0c9e8841f9a9578',
  },
  {
    Title: 'System of a Down',
    Artist: 'System of a Down',
    Rating: 'Gold',
    Descriptors: 'breakdowns, chaotic',
    'Release Date': '1998',
    Spotify: 'https://open.spotify.com/album/3sSfjX4fhZonjyZ10x0l0f',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2732dc63e977bd5101072adcef6',
  },
  {
    Title: 'Data Renaissance',
    Artist: 'The Algorithm',
    Rating: 'Gold',
    Descriptors: 'adventurous, futuristic, instrumental, prog',
    'Release Date': '2022-06-03',
    Spotify: 'https://open.spotify.com/album/1LHSxBpDSoNUrOezwOcLKU',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273005b4f2e229c9380417a57f7',
  },
  {
    Title: 'Ire Works',
    Artist: 'The Dillinger Escape Plan',
    Rating: 'Gold',
    Descriptors: 'chaotic, fun',
    'Release Date': '2007-11-13',
    Spotify: 'https://open.spotify.com/album/65ai7QRrruWGNPcVU23PgD',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273c2b0ced8518ed8905e48c650',
  },
  {
    Title: 'Planetary Duality',
    Artist: 'The Faceless',
    Rating: 'Gold',
    Descriptors: 'adventurous, fast, prog',
    'Release Date': '2008-11-10',
    Spotify: 'https://open.spotify.com/album/1RNJgYpFcDvb607uqTjM54',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2738962b65964307e29940231c2',
  },
  {
    Title: 'Goat',
    Artist: 'The Jesus Lizard',
    Rating: 'Gold',
    Descriptors: 'raw',
    'Release Date': '1991',
    Spotify: 'https://open.spotify.com/album/7uweroXf5R6hWxC1kDXJg3',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b27331797d4a2082d8077e1e38df',
  },
  {
    Title: 'Invaders Must Die',
    Artist: 'The Prodigy',
    Rating: 'Gold',
    Descriptors: 'breakdowns, fun, futuristic',
    'Release Date': '2009-02-23',
    Spotify: 'https://open.spotify.com/album/13PiGMs22YuX1kq7w8WNGM',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273bce53a924b756cbaf8aa245c',
  },
  {
    Title: 'Hatful of Hollow',
    Artist: 'The Smiths',
    Rating: 'Gold',
    Descriptors: 'atmospheric',
    'Release Date': '1984',
    Spotify: 'https://open.spotify.com/album/1j57Q5ntVi7crpibb0h4sv',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273786b44c75ebf915866523f5b',
  },
  {
    Title: 'Broken Soul Jamboree',
    Artist: 'Tipper',
    Rating: 'Gold',
    Descriptors: 'atmospheric, futuristic, soothing',
    'Release Date': '2010-01-01',
    Spotify: 'https://open.spotify.com/album/16rkMVHLdAqlymCww7TDEN',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273df6f4968fda7d1ff1d7563b8',
  },
  {
    Title: 'Ænima',
    Artist: 'Tool',
    Rating: 'Gold',
    Descriptors: 'prog',
    'Release Date': '1996-09-17',
    Spotify: 'https://open.spotify.com/album/6yWMN087PgSimbcVmHLEwG',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273dce45359981d62e087a29e6f',
  },
  {
    Title: 'Lateralus',
    Artist: 'Tool',
    Rating: 'Gold',
    Descriptors: 'prog',
    'Release Date': '2001-05-15',
    Spotify: 'https://open.spotify.com/album/5l5m1hnH4punS1GQXgEi3T',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273ca41a947c13b78749c4953b1',
  },
  {
    Title: 'Nothingface',
    Artist: 'Voivod',
    Rating: 'Gold',
    Descriptors: 'adventurous, prog',
    'Release Date': '1989-01-01',
    Spotify: 'https://open.spotify.com/album/49JPEgPvEaFp89xqzeQvF7',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273bbd0196df4b123504e216405',
  },
  {
    Title: 'EXPLICIT: The MiXXXtape',
    Artist: 'Wargasm',
    Rating: 'Gold',
    Descriptors: 'fun',
    'Release Date': '2022-09-09',
    Spotify: 'https://open.spotify.com/album/0AGZmPToQJuD4DTh6bFGQ2',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b2739be99092e836240f1c2c22b4',
  },
  {
    Title: 'Brotherhood Of Electric',
    Artist: 'Wellwater Conspiracy',
    Rating: 'Gold',
    Descriptors: 'soothing',
    'Release Date': '1999-01-01',
    Spotify: 'https://open.spotify.com/album/2UiG4SGY3eKHVQ6MkzIGYQ',
    Bandcamp: '',
    YouTube: '',
    'Apple Music': '',
    Discovered: '',
    Artwork: 'https://i.scdn.co/image/ab67616d0000b273a781f456e58baf543410bf79',
  },
];
